---
functional:
  - Пользователь должен иметь возможность создавать игру с соперником/другом по ссылке/ботом
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
  - Пользователь должен иметь возможность выбрать сложность игры
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбрать 
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен в реальном времени видеть код соперника, результаты запуска тестов и общаться с ним и зрителями в чате
  - 
non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
