---
functional:
  - Пользователь должен иметь возможность создавать игру с соперником/другом по ссылке/ботом
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен в реальном времени видеть код соперника, результаты запуска тестов и общаться с ним и зрителями в чате
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен иметь регистрационную форму
  - Пользователь должен иметь возможность выбрать сложность игры
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбрать конкретную задачу 
  - Пользователь должен иметь возможность выбрать рандомную задачу
