---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность создавать игру с соперником/другом по ссылке/ботом
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен в реальном времени видеть код соперника, результаты запуска тестов
  - Сайт должен иметь опцию автоматической проверки кода
  - Пользователь должен иметь возможность выбрать сложность игры
  - Пользователь должен иметь возможность выбрать время игры
  - Пользователь должен иметь возможность выбрать конкретную задачу 
  - Пользователь должен иметь возможность выбрать рандомную задачу
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность отменять созданную игру
  - Пользователь должен иметь возможность просматривать историю игры
  - Пользователь должен иметь возможность вернуться в игру после вылета
  - Пользователь должен иметь возможность менять настройки игры (звук, никнейм)
  - На сайте должна присутствовать возможность общения между пользователями
