---
functional:
  - Пользователь должен иметь возможность создавать игру с соперником/другом по ссылке/ботом
  - Пользователь должен иметь возможность присоединиться к уже созданной игре
non-functional:
  - требование 3
  - требование 4
implicit:
  - требование 5
  - требование 6
